apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: k8s-learning
type: Opaque
data:
  SECRET_KEY: cHJvZHVjdGlvbi1zdXBlci1zZWNyZXQtcGxlYXNlLWNoYW5nZQ==
  DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnMjovL2FwcF91c2VyOmFwcF9wYXNzd29yZEBwb3N0Z3Jlczo1NDMyL2FwcF9kYg==
  REDIS_URL: cmVkaXM6Ly9kZWZhdWx0OnlQc1NxanhrMUhDSU42N2tXZTNEWnZDZHc5Vnc4NGE2QHJlZGlzLTE0NjQyLmMyNTkudXMtY2VudHJhbDEtMi5nY2UuY2xvdWQucmVkaXNsYWJzLmNvbToxNDY0Mi8w
  CELERY_BROKER_URL: cmVkaXM6Ly9kZWZhdWx0OnlQc1NxanhrMUhDSU42N2tXZTNEWnZDZHc5Vnc4NGE2QHJlZGlzLTE0NjQyLmMyNTkudXMtY2VudHJhbDEtMi5nY2UuY2xvdWQucmVkaXNsYWJzLmNvbToxNDY0Mi8w
  CELERY_RESULT_BACKEND: cmVkaXM6Ly9kZWZhdWx0OnlQc1NxanhrMUhDSU42N2tXZTNEWnZDZHc5Vnc4NGE2QHJlZGlzLTE0NjQyLmMyNTkudXMtY2VudHJhbDEtMi5nY2UuY2xvdWQucmVkaXNsYWJzLmNvbToxNDY0Mi8w
  POSTGRES_DB: YXBwX2Ri
  POSTGRES_USER: YXBwX3VzZXI=
  POSTGRES_PASSWORD: YXBwX3Bhc3N3b3Jk

