apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: k8s-learning
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: k8s-learning
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: k8s-learning
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: k8s-learning
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend-role

